version: '2.1'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=compair
      - MYSQL_USER=compair
      - MYSQL_PASSWORD=compair
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: always
  redis:
    image: redis:5.0
    command: redis-server --appendonly yes
    volumes:
      - ./.data/redis:/data
    restart: always
  app: &app
    image: "ubcctlt/compair-app:${COMPAIR_VERSION:-latest}"
    environment:
      - DB_DRIVER=mysql+pymysql
      - DB_USERNAME=compair
      - DB_PASSWORD=compair
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=compair
      - SQLALCHEMY_ENGINE_OPTIONS={"pool_recycle":299}
      - CELERY_BROKER_URL=redis://redis:6379
      - ASSET_LOCATION=local
    volumes:
      - ../../.data/persistent:/code/persistent
    depends_on:
      - db
      - redis
    restart: always
  worker: &worker
    <<: *app
    command: celery worker --app=celery_worker.celery --loglevel=INFO
    environment:
      - DB_DRIVER=mysql+pymysql
      - DB_USERNAME=compair
      - DB_PASSWORD=compair
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=compair
      - SQLALCHEMY_ENGINE_OPTIONS={"pool_recycle":299}
      - CELERY_BROKER_URL=redis://redis:6379
      - ASSET_LOCATION=local
      - C_FORCE_ROOT=1
  worker_scheduler:
    <<: *worker
    command: celery beat --app=celery_worker.celery --loglevel=INFO
  web:
    image: nginx:1.11
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../compair/static:/compair/app:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
  worker_monitor:
    image: mher/flower
    command: flower --port=5555 --broker=redis://redis:6379 --basic_auth=user1:password1
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: always
